### ISSUE TITLE
Maintainer is temporarily not using this project so issues and pull requests might be stale

### ISSUE THREAD

**Issue by fliphess** [fliphess/esp8266_p1meter#8]
For those interested in this project: I recently moved to a new home and as a result I'm at this moment not using this project myself. As soon as I've found a post-corona electrician willing to come to my home and create a power outlet next to my DSMR meter i can reinstall this project and fix bugs and add functionality. 

In the meantime: Please fork and create a pull request with fixes if you stumble into repairable issues and manage to work around them. I will get back to you and merge your code changes in the coming months when I can use this project myself again.

**Comment by rcambrj** [comment]
@fliphess I'm going to try implementing this on an ISKRA AM500 (DSMR 5.0) which provides +5V on pin 1. I'm guessing you've checked your meter for this already, but if not, it might save you calling that electrician :)

**Comment by fliphess** [comment]
Hey @rcambrj 

Thanks for your message! 

In my new house I do actually have 5v on the pins, as I have a newer model power meter, so I'm working towards using this model: https://klushok.etv.tudelft.nl/projects/view?id=8

I really like the deepsleep and no need for external power, so as soon as aliexpress has delivered, I'll be back in the game 👍

**Comment by bortek** [comment]
Can anyone clarify what the wiring diagram should be. The image on the first page shows only pinout of RJ11 but how do you wire it to ESP8266?

**Comment by fliphess** [comment]
It's shown 5 lines above the image you mention in `readme.md`. ;)
